language: python
sudo: required
os:
  - linux
dist: trusty

python:
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"

addons:
  postgresql: "10.6"
services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres

script: python test_database.py