language: python
sudo: required
os:
  - linux
dist: trusty
env:
  global:
    - IMAGE_NAME=nikmang/daily-bot
    - secure: ivMpn7YyRHa3nuyzftVBvIslX/GZFP8q/6Uc5LyN9GdpGJFhSJMX008bDbUTz/iJrttln1bDbx1q3357Ke+WR9Z3rmZ35/9wj+BPVJ3eChJBYsSMyi9UyQISEZFEHf/beJaDj1xSSKgmLwEKmOnP1b3iUw75rke99NvZsxlr9C5CUk7j7DW8864dDIVU9z0O5oRYVQ8flkJB/nDDn3ITISjIiehc7HIo6/AvQZ8oz0/ehfzE8m9z0J17b0w9fDsDNeuWGXzARJ2MYef8agTVmJrU3gB9hdZjnCL0eCJYptLgqsuCbzSqSredx3m2HpotDg+6hhe/UUWnQl41l+eLrJKASVMdpeWfmCqaSvOFQGgg95dWobu9+S1nKD75IKhi/I7MCU/3ZnW9f6fY7JkmfC31ikibv0BAvnBZdCj9VOcUznnnlje35skAG9i2euvi7Ng/Uw3BUz+zG+DluMAbbfAk6EvC8TdkDRXPOeBnI42ZsYy2HIivXVSX7g/ef0LbpY8NpEEDHDo+giPuuW9TtRlgsUS6iiNWzKVsdgSFOEyddpbllveWNnRqvC/BxRf4zZDVkiv+edNv7pGlpdBwXSfO+CXgVsunmMO2TkaL9Qn6Rd4FQLO6fS4jgG6eiM/h1t3BXMIeo6DhZQ2PxmIvx1t2S/VkMQeUpxgabLJb/I8=
    - secure: lSupJbb8P6ds1NqcsaDKKZYvHwu7nMzrzrYgf79hVsTfC5nojsrUxRsN5CQKEjZOURLYLUnlGjt3pTzLM7wRblvMJ63nEkWBSubsnkWprYhj8emzt0efYc6PX41PLH9RWjTg4McN60RGXDKUMa1/N0n0D9E/Apy8/G164ZuistOPynexCpo5ZcHS8bPImrkpl3VYjoMCq8NgQEpIEQj5YQFpLMw7n11B3m7EwZpXuQBTrH5hWT4ElxyyQKGn0htaqZw9/iAM/FcJaULxIeqHPKYa0sTW/EkqILsXi+dXno5hAxhrdkF036pefUgVxDg+f8Pd5ThCLvxx1CIN8wcfVQO3cpXqiLAzsIXcWeUHFVblr6qda0GLr5zIsm3IFvc6B62a7/10lyeHNlcX1wFuDzYBQS4AFgZhkkMtnJdpQ/twbX4D7VLnDgzy6AHhnmLjpx6jMJcdBoMtSxHTZMLseEZ2eFNBv7lnOQvo4O+mW0R4zEBTZ/ArC9uLtayzhJG3QQ7F11VOdF/z7fp5hflziCa8QSMWEVIHoVJwgZcuB/zbwGBWf+UVkup5+krlq4gZO25O4QIOC1mWYxRSMnvFZtFX6G1DM2QeiD7C8MEV0rTAaAdwg8d4hYv2sXNWCEEr4+3UggEyMtSXxjhVqye8OuQmwVwsYirejG2WEC/TwNk=
    - secure: lOcSVJKsWffKfZYvza0lrNaCCe+RzCWji4FI2x+wFwrUvKjCQD7qAS+53ofEJQQYvV6SWzQL75JNi40eN4F+Eo8PHcqUBocJnRfvNtGCFgHp5m01iuFgUALBYeEXBjPuxjTkP8Of4T5chn85Lm0WjwHcD4E1gz25NuNFOydeOMti9N3POfxXchiGJdnceH7v5yeELMgthnQLIPeJnZCs3aGfHxFcN0Jw8C7NKwG4x/kGBltVULsxtdHctZullwjmM8sypG/0m7FmPj8DP5/PHlxZSc/yfaa4UWg/Ykm1/2KvKzgWDrJ0XtOX3HfiOwYFKReiq3PdVDt506ZrDdVOJq8AIbVXpspX3OTjHnKoAZe+owDG/rNEu4FPnfQIunH9wMWfdsXNidh2yQM0xQbAhRPDmXKWtTFeFy7Sg81DydIn7cVV60N1TKEzpNTD3eqm3LNtiZRuynn8PYMRcL0qfrjNQijlHAZVO5AvoATYspuDAokyH8sAWK4Bohicoru+oQ5GOcrF2UsbHlTtT6zNF+TKVgGRMiLWuLM/3aT4tSl0k15KlMeEXiuOzoW6lumje6b650Lwr4JPayW42r9xiv33XKuop48rcp3xqz7ai5jaiOFNFmFqnWeymVXrgmv9vkBAe02C/HrxLH9PItL96duHoLh6eBzPGTbJcfbGu0s=
python:
  - '3.5'
  - 3.5-dev
  - '3.6'
  - 3.6-dev
  - 3.7-dev
services:
  - postgresql
  - docker
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres
script: python test_database.py
after_success:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
  - docker build -t $IMAGE_NAME .
  - docker push $IMAGE_NAME
  - docker images
