version: '3.7'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '8080:8080'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'dailybot'
    volumes:
      - ./database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local